# codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# > make sure on codacy dashboard only following engines are enabled

---
engines:
  prospector:
  #    base_sub_dir: "naskpy/"
  remark-lint:
  #  bandit: # used inside prospector
  #  pylintpython3: # we use pep8 inside prospector
  #  markdownlint: # replaced by remark-lint

# exclude_paths: # managed by prospector and remark-lint
#  - "tests/**"
#  - "docs/**"
