# codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

---
engines:
  duplication:
    config:
      languages:
        - "python"
  bandit:
  prospector:
    base_sub_dir: "naskpy/"
  #  pylintpython3:
  remark-lint:
  #  markdownlint:

exclude_paths:
  - "tests/**"
  - "docs/**"
  - "**.yml"
  - "**.yaml"
