# prospector configuration file
# http://prospector.landscape.io/en/master/profiles.html
# http://prospector.landscape.io/en/master/usage.html
output-format: json

strictness: medium
test-warnings: false
doc-warnings: false

#inherits:
#  - strictness_medium
#  - full_pep8

ignore-paths:
  - docs
  - tests

#pep8:
#  disable:
#    - W602
#    - W603
#  enable:
#    - W601
#  options:
#    max-line-length: 79

pep8:
  full: true
  options:
    max-line-length: 79


mccabe:
  run: true
  options:
    max-complexity: 10

bandit:
  run: true
  options:
    min-confidence: 0.9

pylint:
  run: false
dodgy:
  run: false
pyflakes:
  run: false