# prospector configuration file
# http://prospector.landscape.io/en/master/profiles.html
# http://prospector.landscape.io/en/master/usage.html
output-format: json

strictness: medium
test-warnings: false
doc-warnings: false
# member-warnings: false
max-line-length: 120

ignore-paths:
  - docs
  - tests

pep8:
  full: true
  #  disable:
  #    - E501
  #  options:
  #    max-line-length: 79


mccabe:
  run: true
  options:
    max-complexity: 10

bandit:
  run: true
  options:
    min-confidence: 0.9
    config: bandit.yaml

pylint:
  run: false
dodgy:
  run: false
pyflakes:
  run: false