# more at: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# https://docs.readthedocs.io/en/stable/faq.html
# https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#quick-start

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Poetry: https://docs.readthedocs.io/en/stable/guides/poetry.html
python:
  install:
    - method: pip
      path: .