# more at: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# https://docs.readthedocs.io/en/stable/faq.html
# https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#quick-start

version: 2

build:
  image: latest


# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt