# more at: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# https://docs.readthedocs.io/en/stable/faq.html
# https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#quick-start

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt