# remark-lint configuration file
# https://github.com/remarkjs/remark-lint

plugins:
  - "remark-preset-lint-consistent"
  - "remark-preset-lint-recommended"
  - - "remark-lint-list-item-indent"
    - "space"